<?php 
/*-------------------------*/
/* ACTION*/
/*-------------------------*/
/* Simple function to attach to wp_head hook */
function my_custom_function() {
    if(is_home()){
        echo "home";
    }else{
        echo "not home";
    }
}
/* Add the action to wp_head */
add_action( 'wp_head', 'my_custom_function' );


/*-------------------------*/
/* FILTER */
/*-------------------------*/
/*
 * Hook a filter to the excerpt_length to change the number of words printed on a post feed (generated by ./archive.php).
 */
function mytheme_custom_excerpt_length( $length ) {
    // Return new excerpt_length
    return 2;
}
/* Add a filter to the hook 'excerpt_length' */
add_filter( 'excerpt_length', 'mytheme_custom_excerpt_length', 999 );




/*-------------------------*/
/* THEME FUNCTIONS */
/*-------------------------*/
/**
 * Set maximum content width: This limit the width of all uploaded image and embeds.
 */
if ( ! isset( $content_width ) )
    $content_width = 800; // pixels

/**
 * Set up theme defaults and support for various WordPress features.
 *
 * Note that this function is hooked into the after_setup_theme hook, which is before the init hook. The init hook is too late for some features, such as add_theme_support( 'post-thumbnails' ).
 */
if ( !function_exists( 'blank_setup' ) ) :
    function blank_setup(){

        // Make theme available for translation. Translation placed in '/languages/ directory'
        load_theme_textdomain( 'blank', get_template_directory() . '/languages');

        // Allow support for RSS feed link to <head>
        add_theme_support( 'automatic-feed-links' );

        // Enable support for post thumbnails
        add_theme_support( 'post-thumbnails' );

        // Add support for navigation menu
        register_nav_menus( array(
            'primary' => __( 'Primary Menu', 'blank' ),
            'secondary' => __( 'Secondary Menu', 'blank' ),
        ) );

        // Enable support for the following post formats: aside, gallery, quote, image, video
        add_theme_support( 'post-formats', array( 'aside', 'gallery', 'quote', 'image', 'video' ));
    }   
endif;

// Add the action to 'after_setup_theme' hook.
add_action( 'after_setup_theme', 'blank_setup' );
 

/*-------------------------*/
/* ENQUEUING CSS STYLES */
/*-------------------------*/
/** 
 * Remove stylesheet in <link> of the header file. 
 * Enqueue style using Wordpress wp_enqueue_style();
 */
function enqueue_custom_style(){
    // Enqueue the style.css required for this theme.
    // get_stylesheet_url() will return the RELATIVE PATH to the style.css of this theme.
    wp_enqueue_style('theme-style', get_stylesheet_uri());


    // Enqueue the a custom css style. 
    // Note: This will have higher priority than style.css
    // Note: Use get_template_directory_uri() to get the RELATIVE PATH
    // Note: Using get_template_directory() will return the ABSOLUTE PATH
    wp_enqueue_style('custom-style', get_template_directory_uri() . '/css/custom.css', false, '1.1', 'all');
}
add_action('wp_enqueue_scripts', 'enqueue_custom_style');


/*-------------------------*/
/* ENQUEUING JAVASCRIPT */
/*-------------------------*/
/**
 * TODO: Add Javascript the same way as style add except with wp_enqueue_script
 */
